name: Deploy Wireframe to GitHub Pages

on:
  push:
    branches:
      - main  # Spustí se pokaždé, když nahraješ něco do větve main

permissions:
  contents: write

jobs:
  deploy:
    runs-level: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Wireframe # Tady říkáme, že chceme vzít JEN obsah této složky
          branch: gh-pages  # A nahrát ho do speciální větve
